### PR TITLE
Better Optional Handling

### PR DESCRIPTION
**Pull request by NoahDavey**
Hey this is just a small PR looking to address the issue of optionals not being handled quite as they should be. I ran into the issue while using the library to generate my types

I noticed there is a [PR](https://github.com/sachinraja/zod-to-ts/pull/10) looking to do a similar thing currently but I do not think there is a need for a flag tbh. I agree with [robins comment](https://github.com/sachinraja/zod-to-ts/pull/10#issuecomment-1107540939) around the best idea being to aim to be as close as possible to the resulting types from `z.infer`

The main shortfall I would callout in this PR is that the `or` type 
`or: z.number().optional().or(z.string())` which transforms into `or?: (number | undefined) | string;`
Should actually look like `or?: number | undefined | string;` but think it is alright leaving that for now as a future improvement

Keen to get something like this in if possible since atm I am probably going to have to resort to using z.infer in a few places instead of my generated types!

### CODE REVIEW

**Comment by sachinraja** [comment]
This is the same problem that we had in the other PR so I was reluctant to merge it. I guess this can be done for now though. I'll release this later today.

There seems to be a lot of people who want this though so I will take another look at how we can implement this. I think we can use a TS transformer to traverse all the nodes after they are generated.

**Review by sachinraja — APPROVED** [review]

**Comment by NoahDavey** [comment]
> Is there a functional difference? Or would that just be for prettier output?

Unsure if functionally different, but definitely different than the output of `z.infer<T>` may or may not lead to type mismatch issues, but don't know without playing around with it. Main reason I raised PR originally was having issues where even though `prop: string | undefined` is probably equivalent to `prop?: string | undefined` in most cases i was having TS compiler issues where it was complaining they were different

**Comment by sachinraja** [comment]
Ok, thanks for clarifying. I believe they're the same so I'll go ahead and merge this now :+1:

**Comment by sachinraja** [comment]
@mordv @RobinTail I've released a new version (`1.0.0`) with this fix. Does that fix the issues you were having?

**Comment by sachinraja** [comment]
@gtflip I believe it may change behavior [depending on your tsconfig](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes)

**Comment by gtflip** [comment]
> @gtflip I believe it may change behavior [depending on your tsconfig](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes). Also I'm not too concerned with prettier output at the moment. I think it would actually be difficult to not omit `undefined`.

I didn't know about that tsconfig option.  Thanks for responding.

I'm using it to document what the types look like for API calls, so that's why I was thinking in terms of it being easier to read.  I can just edit the output, though.

**Pull request merged**
